// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wakatime_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	Username  string
	Email     pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type WakatimeDay struct {
	ID           int32
	UserID       pgtype.UUID
	Date         pgtype.Date
	TotalSeconds float64
	Text         pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WakatimeDependency struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      pgtype.Float8
	Text         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type WakatimeEditor struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      pgtype.Float8
	Text         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type WakatimeLanguage struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      pgtype.Float8
	Text         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type WakatimeMachine struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      pgtype.Float8
	Text         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type WakatimeO struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      pgtype.Float8
	Text         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type WakatimeProject struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      pgtype.Float8
	Text         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type WakatimeSummary struct {
	ID           int32
	UserID       pgtype.UUID
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Range        pgtype.Text
	TotalSeconds pgtype.Float8
	DailyAverage pgtype.Float8
	BestDayID    pgtype.Int4
	CreatedAt    pgtype.Timestamptz
}
