// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wakatime_db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Username  string
	Email     sql.NullString
	CreatedAt sql.NullTime
}

type WakatimeDay struct {
	ID           int32
	UserID       uuid.UUID
	Date         time.Time
	TotalSeconds float64
	Text         sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type WakatimeDependency struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      sql.NullFloat64
	Text         sql.NullString
	CreatedAt    sql.NullTime
}

type WakatimeEditor struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      sql.NullFloat64
	Text         sql.NullString
	CreatedAt    sql.NullTime
}

type WakatimeLanguage struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      sql.NullFloat64
	Text         sql.NullString
	CreatedAt    sql.NullTime
}

type WakatimeMachine struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      sql.NullFloat64
	Text         sql.NullString
	CreatedAt    sql.NullTime
}

type WakatimeO struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      sql.NullFloat64
	Text         sql.NullString
	CreatedAt    sql.NullTime
}

type WakatimeProject struct {
	ID           int32
	DayID        int32
	Name         string
	TotalSeconds float64
	Percent      sql.NullFloat64
	Text         sql.NullString
	CreatedAt    sql.NullTime
}

type WakatimeSummary struct {
	ID           int32
	UserID       uuid.UUID
	StartTime    time.Time
	EndTime      time.Time
	Range        sql.NullString
	TotalSeconds sql.NullFloat64
	DailyAverage sql.NullFloat64
	BestDayID    sql.NullInt32
	CreatedAt    sql.NullTime
}
