// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package activitywatch_db

import (
	"context"
)

// iteratorForBatchInsertActivityEvents implements pgx.CopyFromSource.
type iteratorForBatchInsertActivityEvents struct {
	rows                 []BatchInsertActivityEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertActivityEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertActivityEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Timestamp,
		r.rows[0].Duration,
		r.rows[0].App,
		r.rows[0].Title,
		r.rows[0].BucketID,
	}, nil
}

func (r iteratorForBatchInsertActivityEvents) Err() error {
	return nil
}

func (q *Queries) BatchInsertActivityEvents(ctx context.Context, arg []BatchInsertActivityEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"activity_events"}, []string{"id", "timestamp", "duration", "app", "title", "bucket_id"}, &iteratorForBatchInsertActivityEvents{rows: arg})
}
