// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package activitywatch_db

import (
	"context"
)

// iteratorForBulkInsertEvents implements pgx.CopyFromSource.
type iteratorForBulkInsertEvents struct {
	rows                 []BulkInsertEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Timestamp,
		r.rows[0].Duration,
		r.rows[0].App,
		r.rows[0].Title,
		r.rows[0].BucketID,
	}, nil
}

func (r iteratorForBulkInsertEvents) Err() error {
	return nil
}

func (q *Queries) BulkInsertEvents(ctx context.Context, arg []BulkInsertEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"activity_events"}, []string{"timestamp", "duration", "app", "title", "bucket_id"}, &iteratorForBulkInsertEvents{rows: arg})
}
