// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package activitywatch_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityEvent struct {
	ID        int64
	Timestamp pgtype.Timestamptz
	Duration  float64
	App       string
	Title     pgtype.Text
	BucketID  string
	CreatedAt pgtype.Timestamptz
}
