// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package googlefit_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GooglefitDailyStat struct {
	ID        int32
	UserID    pgtype.UUID
	Date      pgtype.Date
	Steps     pgtype.Int4
	Distance  pgtype.Float8
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
