// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: googlecalendar_queries.sql

package googlecalendar_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one

INSERT INTO googlecalendar_events (
    user_id, event_id, calendar_id, summary, description, location,
    start_time, end_time, is_all_day, duration, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, event_id, calendar_id, summary, description, location, start_time, end_time, is_all_day, duration, status, created_at, updated_at
`

type CreateEventParams struct {
	UserID      pgtype.UUID
	EventID     string
	CalendarID  string
	Summary     pgtype.Text
	Description pgtype.Text
	Location    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	IsAllDay    pgtype.Bool
	Duration    pgtype.Int4
	Status      pgtype.Text
}

// Events Queries -------------------------------------------------------------------
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (GooglecalendarEvent, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.UserID,
		arg.EventID,
		arg.CalendarID,
		arg.Summary,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.IsAllDay,
		arg.Duration,
		arg.Status,
	)
	var i GooglecalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.IsAllDay,
		&i.Duration,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM googlecalendar_events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getAverageDailyEvents = `-- name: GetAverageDailyEvents :one
SELECT
    AVG(event_count)::FLOAT as avg_events_per_day,
    AVG(total_duration)::FLOAT as avg_duration_per_day
FROM (
    SELECT
        DATE(start_time) as event_date,
        COUNT(*) as event_count,
        SUM(duration) as total_duration
    FROM googlecalendar_events
    WHERE user_id = $1
      AND start_time >= $2
      AND end_time <= $3
    GROUP BY DATE(start_time)
) AS daily_stats
`

type GetAverageDailyEventsParams struct {
	UserID    pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

type GetAverageDailyEventsRow struct {
	AvgEventsPerDay   float64
	AvgDurationPerDay float64
}

func (q *Queries) GetAverageDailyEvents(ctx context.Context, arg GetAverageDailyEventsParams) (GetAverageDailyEventsRow, error) {
	row := q.db.QueryRow(ctx, getAverageDailyEvents, arg.UserID, arg.StartTime, arg.EndTime)
	var i GetAverageDailyEventsRow
	err := row.Scan(&i.AvgEventsPerDay, &i.AvgDurationPerDay)
	return i, err
}

const getBusiestDays = `-- name: GetBusiestDays :many
SELECT
    DATE(start_time) as event_date,
    COUNT(*) as event_count,
    SUM(duration) as total_duration_minutes
FROM googlecalendar_events
WHERE user_id = $1
  AND start_time >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY DATE(start_time)
ORDER BY event_count DESC, total_duration_minutes DESC
LIMIT $2
`

type GetBusiestDaysParams struct {
	UserID pgtype.UUID
	Limit  int32
}

type GetBusiestDaysRow struct {
	EventDate            pgtype.Date
	EventCount           int64
	TotalDurationMinutes int64
}

func (q *Queries) GetBusiestDays(ctx context.Context, arg GetBusiestDaysParams) ([]GetBusiestDaysRow, error) {
	rows, err := q.db.Query(ctx, getBusiestDays, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBusiestDaysRow
	for rows.Next() {
		var i GetBusiestDaysRow
		if err := rows.Scan(&i.EventDate, &i.EventCount, &i.TotalDurationMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyEventsSummary = `-- name: GetDailyEventsSummary :many

SELECT
    DATE(start_time) as event_date,
    COUNT(*) as total_events,
    SUM(duration) as total_duration_minutes,
    COUNT(CASE WHEN is_all_day THEN 1 END) as all_day_events
FROM googlecalendar_events
WHERE user_id = $1
  AND start_time >= $2
  AND end_time <= $3
GROUP BY DATE(start_time)
ORDER BY event_date DESC
`

type GetDailyEventsSummaryParams struct {
	UserID    pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

type GetDailyEventsSummaryRow struct {
	EventDate            pgtype.Date
	TotalEvents          int64
	TotalDurationMinutes int64
	AllDayEvents         int64
}

// Analytics Queries -------------------------------------------------------------------
func (q *Queries) GetDailyEventsSummary(ctx context.Context, arg GetDailyEventsSummaryParams) ([]GetDailyEventsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getDailyEventsSummary, arg.UserID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyEventsSummaryRow
	for rows.Next() {
		var i GetDailyEventsSummaryRow
		if err := rows.Scan(
			&i.EventDate,
			&i.TotalEvents,
			&i.TotalDurationMinutes,
			&i.AllDayEvents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, user_id, event_id, calendar_id, summary, description, location, start_time, end_time, is_all_day, duration, status, created_at, updated_at FROM googlecalendar_events WHERE user_id = $1 AND event_id = $2
`

type GetEventByIDParams struct {
	UserID  pgtype.UUID
	EventID string
}

func (q *Queries) GetEventByID(ctx context.Context, arg GetEventByIDParams) (GooglecalendarEvent, error) {
	row := q.db.QueryRow(ctx, getEventByID, arg.UserID, arg.EventID)
	var i GooglecalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.IsAllDay,
		&i.Duration,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventsByCalendarSummary = `-- name: GetEventsByCalendarSummary :many
SELECT
    calendar_id,
    COUNT(*) as total_events,
    SUM(duration) as total_duration_minutes
FROM googlecalendar_events
WHERE user_id = $1
  AND start_time >= $2
  AND end_time <= $3
GROUP BY calendar_id
ORDER BY total_events DESC
`

type GetEventsByCalendarSummaryParams struct {
	UserID    pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

type GetEventsByCalendarSummaryRow struct {
	CalendarID           string
	TotalEvents          int64
	TotalDurationMinutes int64
}

func (q *Queries) GetEventsByCalendarSummary(ctx context.Context, arg GetEventsByCalendarSummaryParams) ([]GetEventsByCalendarSummaryRow, error) {
	rows, err := q.db.Query(ctx, getEventsByCalendarSummary, arg.UserID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByCalendarSummaryRow
	for rows.Next() {
		var i GetEventsByCalendarSummaryRow
		if err := rows.Scan(&i.CalendarID, &i.TotalEvents, &i.TotalDurationMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByCalendar = `-- name: ListEventsByCalendar :many
SELECT id, user_id, event_id, calendar_id, summary, description, location, start_time, end_time, is_all_day, duration, status, created_at, updated_at FROM googlecalendar_events
WHERE user_id = $1 AND calendar_id = $2
ORDER BY start_time DESC
LIMIT $3 OFFSET $4
`

type ListEventsByCalendarParams struct {
	UserID     pgtype.UUID
	CalendarID string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListEventsByCalendar(ctx context.Context, arg ListEventsByCalendarParams) ([]GooglecalendarEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByCalendar,
		arg.UserID,
		arg.CalendarID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GooglecalendarEvent
	for rows.Next() {
		var i GooglecalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.IsAllDay,
			&i.Duration,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByDate = `-- name: ListEventsByDate :many
SELECT id, user_id, event_id, calendar_id, summary, description, location, start_time, end_time, is_all_day, duration, status, created_at, updated_at FROM googlecalendar_events
WHERE user_id = $1 AND DATE(start_time) = $2
ORDER BY start_time ASC
`

type ListEventsByDateParams struct {
	UserID    pgtype.UUID
	StartTime pgtype.Timestamptz
}

func (q *Queries) ListEventsByDate(ctx context.Context, arg ListEventsByDateParams) ([]GooglecalendarEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByDate, arg.UserID, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GooglecalendarEvent
	for rows.Next() {
		var i GooglecalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.IsAllDay,
			&i.Duration,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByDateRange = `-- name: ListEventsByDateRange :many
SELECT id, user_id, event_id, calendar_id, summary, description, location, start_time, end_time, is_all_day, duration, status, created_at, updated_at FROM googlecalendar_events
WHERE user_id = $1 AND start_time >= $2 AND end_time <= $3
ORDER BY start_time ASC
`

type ListEventsByDateRangeParams struct {
	UserID    pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

func (q *Queries) ListEventsByDateRange(ctx context.Context, arg ListEventsByDateRangeParams) ([]GooglecalendarEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByDateRange, arg.UserID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GooglecalendarEvent
	for rows.Next() {
		var i GooglecalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.IsAllDay,
			&i.Duration,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByUser = `-- name: ListEventsByUser :many
SELECT id, user_id, event_id, calendar_id, summary, description, location, start_time, end_time, is_all_day, duration, status, created_at, updated_at FROM googlecalendar_events
WHERE user_id = $1
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type ListEventsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListEventsByUser(ctx context.Context, arg ListEventsByUserParams) ([]GooglecalendarEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GooglecalendarEvent
	for rows.Next() {
		var i GooglecalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.IsAllDay,
			&i.Duration,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE googlecalendar_events
SET summary = $2, description = $3, location = $4,
    start_time = $5, end_time = $6, is_all_day = $7,
    duration = $8, status = $9, updated_at = now()
WHERE id = $1
RETURNING id, user_id, event_id, calendar_id, summary, description, location, start_time, end_time, is_all_day, duration, status, created_at, updated_at
`

type UpdateEventParams struct {
	ID          int32
	Summary     pgtype.Text
	Description pgtype.Text
	Location    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	IsAllDay    pgtype.Bool
	Duration    pgtype.Int4
	Status      pgtype.Text
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (GooglecalendarEvent, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Summary,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.IsAllDay,
		arg.Duration,
		arg.Status,
	)
	var i GooglecalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.IsAllDay,
		&i.Duration,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEvent = `-- name: UpsertEvent :one
INSERT INTO googlecalendar_events (
    user_id, event_id, calendar_id, summary, description, location,
    start_time, end_time, is_all_day, duration, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id, event_id)
DO UPDATE SET
    calendar_id = EXCLUDED.calendar_id,
    summary = EXCLUDED.summary,
    description = EXCLUDED.description,
    location = EXCLUDED.location,
    start_time = EXCLUDED.start_time,
    end_time = EXCLUDED.end_time,
    is_all_day = EXCLUDED.is_all_day,
    duration = EXCLUDED.duration,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING id, user_id, event_id, calendar_id, summary, description, location, start_time, end_time, is_all_day, duration, status, created_at, updated_at
`

type UpsertEventParams struct {
	UserID      pgtype.UUID
	EventID     string
	CalendarID  string
	Summary     pgtype.Text
	Description pgtype.Text
	Location    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	IsAllDay    pgtype.Bool
	Duration    pgtype.Int4
	Status      pgtype.Text
}

func (q *Queries) UpsertEvent(ctx context.Context, arg UpsertEventParams) (GooglecalendarEvent, error) {
	row := q.db.QueryRow(ctx, upsertEvent,
		arg.UserID,
		arg.EventID,
		arg.CalendarID,
		arg.Summary,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.IsAllDay,
		arg.Duration,
		arg.Status,
	)
	var i GooglecalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.IsAllDay,
		&i.Duration,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
