// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package googlecalendar_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GooglecalendarEvent struct {
	ID          int32
	UserID      pgtype.UUID
	EventID     string
	CalendarID  string
	Summary     pgtype.Text
	Description pgtype.Text
	Location    pgtype.Text
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	IsAllDay    pgtype.Bool
	Duration    pgtype.Int4
	Status      pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
